name = "NonResizableVectors"
uuid = "7f57ccbd-1551-4290-8d6c-558f708f8ba7"
authors = ["Neven Sajko <s@purelymail.com> and contributors"]
version = "1.0.0"

[compat]
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
